use std::collections::BTreeSet;

use crate::semantics::cps::effect_marker::CpsInfo;
use crate::semantics::meta::runtime_ast::{RuntimeAst, RuntimeExpr, RuntimeStmt};
use crate::util::id_provider::IdProvider;
use crate::util::node_id::RuntimeNodeId;

// ── Public entry point ────────────────────────────────────────────────────────

/// Apply the full CPS transform, including converting while loops that contain ctl
/// ops into tail-recursive helper functions. Returns the transformed AST.
///
/// Takes ownership so that a panic mid-transform cannot leave a partially-rewritten
/// AST visible to subsequent passes. Either the caller gets back a fully-transformed
/// AST, or the process panics — there is no intermediate broken state.
///
/// Use this for the **codegen** (LLVM) path.
pub fn transform(ast: RuntimeAst, info: &CpsInfo) -> RuntimeAst {
    let mut ast = ast;
    transform_internal(&mut ast, info, true);
    ast
}

/// Apply the CPS transform **without** converting while loops to tail-recursive
/// helpers. Returns the transformed AST.
///
/// Takes ownership for the same atomicity guarantee as `transform`.
///
/// Use this for the **interpreter** path when while-loop recursion is undesirable.
pub fn transform_interpreter(ast: RuntimeAst, info: &CpsInfo) -> RuntimeAst {
    let mut ast = ast;
    transform_internal(&mut ast, info, false);
    ast
}

fn transform_internal(ast: &mut RuntimeAst, info: &CpsInfo, convert_while_loops: bool) {
    if info.cps_fns.is_empty() && info.ctl_ops.is_empty() {
        return;
    }

    let mut t = CpsTransform {
        info,
        ids: IdProvider::starting_from(ast.next_id),
        new_fndecls: Vec::new(),
        convert_while_loops,
        current_k_name: "__k".to_string(),
    };

    // Transform all CPS FnDecl bodies.
    let fn_stmt_ids: Vec<RuntimeNodeId> = ast.stmts.keys().copied().collect();
    for stmt_id in fn_stmt_ids {
        if let Some(RuntimeStmt::FnDecl { name, .. }) = ast.get_stmt(stmt_id) {
            if info.cps_fns.contains(name.as_str()) {
                t.transform_fn_decl(ast, stmt_id);
            }
        }
    }

    // Transform the top-level sequence for any CPS calls there.
    let root = std::mem::take(&mut ast.sem_root_stmts);
    ast.sem_root_stmts = t.transform_stmts(ast, &root, false);

    // Append any helper FnDecls generated by loop-to-recursion transforms.
    ast.sem_root_stmts.extend(t.new_fndecls.iter().copied());
}

// ── Internal state ────────────────────────────────────────────────────────────

struct CpsTransform<'a> {
    info: &'a CpsInfo,
    ids: IdProvider,
    /// New FnDecl stmt ids created by loop-to-recursion transforms.
    new_fndecls: Vec<RuntimeNodeId>,
    convert_while_loops: bool,
    /// The continuation parameter name for the CPS function currently being transformed.
    current_k_name: String,
}

struct CpsCall {
    callee: String,
    args: Vec<RuntimeNodeId>,
    binding: Option<String>,
}

impl<'a> CpsTransform<'a> {
    // ── FnDecl ────────────────────────────────────────────────────────────────

    fn transform_fn_decl(&mut self, ast: &mut RuntimeAst, stmt_id: RuntimeNodeId) {
        let (name, mut params, type_params, body_id) =
            match ast.get_stmt(stmt_id).unwrap().clone() {
                RuntimeStmt::FnDecl { name, params, type_params, body } => {
                    (name, params, type_params, body)
                }
                _ => return,
            };

        let k_name = format!("__k_{}", stmt_id.0);
        self.current_k_name = k_name.clone();
        params.push(k_name);

        let stmts = match ast.get_stmt(body_id).unwrap().clone() {
            RuntimeStmt::Block(s) => s,
            _ => vec![body_id],
        };

        let transformed = self.transform_stmts(ast, &stmts, true);
        let new_body = self.fresh_stmt(ast, RuntimeStmt::Block(transformed));

        ast.insert_stmt(
            stmt_id,
            RuntimeStmt::FnDecl { name, params, type_params, body: new_body },
        );
    }

    // ── Statement sequence ────────────────────────────────────────────────────

    fn transform_stmts(
        &mut self,
        ast: &mut RuntimeAst,
        stmts: &[RuntimeNodeId],
        is_cps_body: bool,
    ) -> Vec<RuntimeNodeId> {
        let stmts = flatten_stmt_list(ast, stmts);

        let mut result: Vec<RuntimeNodeId> = Vec::new();

        let mut i = 0;
        while i < stmts.len() {
            let stmt_id = stmts[i];

            if is_cps_body {
                if let Some(k_call) = self.try_transform_return(ast, stmt_id) {
                    result.push(k_call);
                    return result;
                }
            }

            if self.convert_while_loops
                && matches!(ast.get_stmt(stmt_id), Some(RuntimeStmt::WhileLoop { .. }))
                && stmt_has_ctl_ops(ast, stmt_id, self.info)
            {
                let replacement = self.transform_while_loop(ast, stmt_id, &stmts[i + 1..], is_cps_body);
                result.extend(replacement);
                return result;
            }

            if let Some(RuntimeStmt::If { cond, body, else_branch }) = ast.get_stmt(stmt_id) {
                let (cond_id, body_id, else_id) = (*cond, *body, *else_branch);
                if let Some(RuntimeExpr::Call { callee, args }) = ast.get_expr(cond_id) {
                    if self.is_cps_callee(callee) {
                        let callee = callee.clone();
                        let ctl_args = args.clone();
                        let replacement = self.transform_if_ctl_cond(
                            ast, callee, ctl_args, body_id, else_id, &stmts[i + 1..], is_cps_body,
                        );
                        result.extend(replacement);
                        return result;
                    }
                }
            }

            let is_handle_callee = match ast.get_stmt(stmt_id) {
                Some(RuntimeStmt::VarDecl { expr, .. }) | Some(RuntimeStmt::ExprStmt(expr)) => {
                    matches!(ast.get_expr(*expr),
                        Some(RuntimeExpr::Call { callee, .. }) if callee.starts_with("__handle_"))
                }
                _ => false,
            };
            let should_extract = is_cps_body || !is_handle_callee;

            if should_extract {
                if let Some(call) = self.extract_cps_call(ast, stmt_id) {
                    let suffix_transformed = self.transform_stmts(ast, &stmts[i + 1..], is_cps_body);

                    let body_stmts = if is_cps_body && suffix_transformed.is_empty() {
                        vec![self.make_k_unit_call(ast)]
                    } else {
                        suffix_transformed
                    };

                    let cont_param = call.binding.unwrap_or_else(|| "__".to_string());
                    let lambda_body = self.fresh_stmt(ast, RuntimeStmt::Block(body_stmts));
                    let lambda = self.fresh_expr(
                        ast,
                        RuntimeExpr::Lambda { params: vec![cont_param], body: lambda_body },
                    );

                    let mut new_args = call.args;
                    new_args.push(lambda);
                    let call_expr =
                        self.fresh_expr(ast, RuntimeExpr::Call { callee: call.callee, args: new_args });
                    let call_stmt = if is_cps_body {
                        self.fresh_stmt(ast, RuntimeStmt::Return(Some(call_expr)))
                    } else {
                        self.fresh_stmt(ast, RuntimeStmt::ExprStmt(call_expr))
                    };

                    result.push(call_stmt);
                    return result;
                }
            }

            result.push(stmt_id);
            i += 1;
        }

        if is_cps_body {
            result.push(self.make_k_unit_call(ast));
        }

        result
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    fn try_transform_return(&mut self, ast: &mut RuntimeAst, stmt_id: RuntimeNodeId) -> Option<RuntimeNodeId> {
        match ast.get_stmt(stmt_id)?.clone() {
            RuntimeStmt::Return(opt_expr) => {
                let val = opt_expr.unwrap_or_else(|| self.fresh_expr(ast, RuntimeExpr::Unit));
                let k = self.current_k_name.clone();
                let call = self.fresh_expr(
                    ast,
                    RuntimeExpr::Call { callee: k, args: vec![val] },
                );
                Some(self.fresh_stmt(ast, RuntimeStmt::Return(Some(call))))
            }
            _ => None,
        }
    }

    fn make_k_unit_call(&mut self, ast: &mut RuntimeAst) -> RuntimeNodeId {
        let unit = self.fresh_expr(ast, RuntimeExpr::Unit);
        let k = self.current_k_name.clone();
        let call = self.fresh_expr(ast, RuntimeExpr::Call { callee: k, args: vec![unit] });
        self.fresh_stmt(ast, RuntimeStmt::Return(Some(call)))
    }

    fn extract_cps_call(&self, ast: &RuntimeAst, stmt_id: RuntimeNodeId) -> Option<CpsCall> {
        match ast.get_stmt(stmt_id)? {
            RuntimeStmt::VarDecl { name, expr } => {
                if let Some(RuntimeExpr::Call { callee, args }) = ast.get_expr(*expr) {
                    if self.is_cps_callee(callee) {
                        return Some(CpsCall {
                            callee: callee.clone(),
                            args: args.clone(),
                            binding: Some(name.clone()),
                        });
                    }
                }
                None
            }
            RuntimeStmt::ExprStmt(expr) => {
                if let Some(RuntimeExpr::Call { callee, args }) = ast.get_expr(*expr) {
                    if self.is_cps_callee(callee) {
                        return Some(CpsCall {
                            callee: callee.clone(),
                            args: args.clone(),
                            binding: None,
                        });
                    }
                }
                None
            }
            _ => None,
        }
    }

    fn is_cps_callee(&self, callee: &str) -> bool {
        self.info.ctl_ops.contains(callee) || self.info.cps_fns.contains(callee)
    }

    // ── WhileLoop → tail-recursive helper function ───────────────────────────

    fn transform_while_loop(
        &mut self,
        ast: &mut RuntimeAst,
        while_stmt_id: RuntimeNodeId,
        suffix: &[RuntimeNodeId],
        is_cps_body: bool,
    ) -> Vec<RuntimeNodeId> {
        let (cond_id, body_id) = match ast.get_stmt(while_stmt_id) {
            Some(RuntimeStmt::WhileLoop { cond, body }) => (*cond, *body),
            _ => return vec![while_stmt_id],
        };

        let flat_body = flatten_stmt_list(ast, &[body_id]);

        let mut assigns: Vec<(String, RuntimeNodeId)> = Vec::new();
        let mut non_assigns: Vec<RuntimeNodeId> = Vec::new();
        for &sid in &flat_body {
            match ast.get_stmt(sid) {
                Some(RuntimeStmt::Assign { name, expr }) => {
                    assigns.push((name.clone(), *expr));
                }
                _ => non_assigns.push(sid),
            }
        }

        let assigned_names: BTreeSet<String> =
            assigns.iter().map(|(n, _)| n.clone()).collect();
        let locally_declared: BTreeSet<String> = flat_body.iter()
            .filter_map(|&sid| {
                if let Some(RuntimeStmt::VarDecl { name, .. }) = ast.get_stmt(sid) {
                    Some(name.clone())
                } else {
                    None
                }
            })
            .collect();
        let mut refs: BTreeSet<String> = BTreeSet::new();
        collect_stmt_refs(ast, body_id, &assigned_names, &mut refs);
        collect_expr_refs(ast, cond_id, &assigned_names, &mut refs);
        let outer_k = self.current_k_name.clone();
        let captured_vars: Vec<String> = refs
            .into_iter()
            .filter(|r| {
                !self.info.ctl_ops.contains(r.as_str())
                    && r.as_str() != outer_k.as_str()
                    && !locally_declared.contains(r.as_str())
            })
            .collect();

        let helper_name = format!("__loop_{}", while_stmt_id.0);

        let mut helper_params: Vec<String> =
            assigns.iter().map(|(n, _)| n.clone()).collect();
        helper_params.extend(captured_vars.iter().cloned());
        helper_params.push("__k".to_string());

        let mut recursive_args: Vec<RuntimeNodeId> = Vec::new();
        for (_, update_expr) in &assigns {
            recursive_args.push(*update_expr);
        }
        for cap in &captured_vars {
            recursive_args.push(self.fresh_expr(ast, RuntimeExpr::Variable(cap.clone())));
        }
        recursive_args.push(self.fresh_expr(ast, RuntimeExpr::Variable("__k".to_string())));
        let recursive_call_expr = self.fresh_expr(ast, RuntimeExpr::Call {
            callee: helper_name.clone(),
            args: recursive_args,
        });
        let recursive_call_stmt = self.fresh_stmt(ast, RuntimeStmt::ExprStmt(recursive_call_expr));

        let mut body_for_cps = non_assigns;
        body_for_cps.push(recursive_call_stmt);
        let cps_body = self.transform_stmts(ast, &body_for_cps, false);

        let true_block = self.fresh_stmt(ast, RuntimeStmt::Block(cps_body));

        let unit_e = self.fresh_expr(ast, RuntimeExpr::Unit);
        let k_done = self.fresh_expr(ast, RuntimeExpr::Call {
            callee: "__k".to_string(),
            args: vec![unit_e],
        });
        let k_done_stmt = self.fresh_stmt(ast, RuntimeStmt::ExprStmt(k_done));
        let false_block = self.fresh_stmt(ast, RuntimeStmt::Block(vec![k_done_stmt]));

        let if_stmt = self.fresh_stmt(ast, RuntimeStmt::If {
            cond: cond_id,
            body: true_block,
            else_branch: Some(false_block),
        });

        let helper_body = self.fresh_stmt(ast, RuntimeStmt::Block(vec![if_stmt]));
        let helper_decl = self.fresh_stmt(ast, RuntimeStmt::FnDecl {
            name: helper_name.clone(),
            params: helper_params.clone(),
            type_params: vec![],
            body: helper_body,
        });
        self.new_fndecls.push(helper_decl);

        let loop_k = if suffix.is_empty() && is_cps_body {
            self.fresh_expr(ast, RuntimeExpr::Variable(outer_k))
        } else {
            let suffix_transformed = self.transform_stmts(ast, suffix, is_cps_body);
            let suffix_body = self.fresh_stmt(ast, RuntimeStmt::Block(suffix_transformed));
            self.fresh_expr(ast, RuntimeExpr::Lambda {
                params: vec!["__".to_string()],
                body: suffix_body,
            })
        };

        let mut init_args: Vec<RuntimeNodeId> = Vec::new();
        for (var_name, _) in &assigns {
            init_args.push(self.fresh_expr(ast, RuntimeExpr::Variable(var_name.clone())));
        }
        for cap in &captured_vars {
            init_args.push(self.fresh_expr(ast, RuntimeExpr::Variable(cap.clone())));
        }
        init_args.push(loop_k);
        let init_call = self.fresh_expr(ast, RuntimeExpr::Call {
            callee: helper_name,
            args: init_args,
        });
        let init_stmt = self.fresh_stmt(ast, RuntimeStmt::ExprStmt(init_call));

        vec![init_stmt]
    }

    // ── If with ctl condition ─────────────────────────────────────────────────

    fn transform_if_ctl_cond(
        &mut self,
        ast: &mut RuntimeAst,
        callee: String,
        ctl_args: Vec<RuntimeNodeId>,
        body: RuntimeNodeId,
        else_branch: Option<RuntimeNodeId>,
        suffix: &[RuntimeNodeId],
        is_cps_body: bool,
    ) -> Vec<RuntimeNodeId> {
        let result_var = "__result".to_string();
        let result_var_expr = self.fresh_expr(ast, RuntimeExpr::Variable(result_var.clone()));

        let new_if = self.fresh_stmt(ast, RuntimeStmt::If {
            cond: result_var_expr,
            body,
            else_branch,
        });

        let mut cont_body = vec![new_if];
        cont_body.extend_from_slice(suffix);
        let cont_transformed = self.transform_stmts(ast, &cont_body, is_cps_body);

        let lambda_body = self.fresh_stmt(ast, RuntimeStmt::Block(cont_transformed));
        let lambda = self.fresh_expr(ast, RuntimeExpr::Lambda {
            params: vec![result_var],
            body: lambda_body,
        });

        let mut new_args = ctl_args;
        new_args.push(lambda);
        let call_expr = self.fresh_expr(ast, RuntimeExpr::Call { callee, args: new_args });
        let call_stmt = self.fresh_stmt(ast, RuntimeStmt::ExprStmt(call_expr));

        vec![call_stmt]
    }

    fn fresh_expr(&mut self, ast: &mut RuntimeAst, expr: RuntimeExpr) -> RuntimeNodeId {
        let id = self.ids.next_runtime();
        ast.insert_expr(id, expr);
        id
    }

    fn fresh_stmt(&mut self, ast: &mut RuntimeAst, stmt: RuntimeStmt) -> RuntimeNodeId {
        let id = self.ids.next_runtime();
        ast.insert_stmt(id, stmt);
        id
    }
}

// ── Free-standing helpers ─────────────────────────────────────────────────────

fn flatten_stmt_list(ast: &RuntimeAst, stmts: &[RuntimeNodeId]) -> Vec<RuntimeNodeId> {
    stmts.iter().copied()
        .flat_map(|id| flatten_one(ast, id))
        .collect()
}

fn flatten_one(ast: &RuntimeAst, stmt_id: RuntimeNodeId) -> Vec<RuntimeNodeId> {
    match ast.get_stmt(stmt_id) {
        Some(RuntimeStmt::Block(inner)) => {
            let inner = inner.clone();
            inner.into_iter().flat_map(|id| flatten_one(ast, id)).collect()
        }
        _ => vec![stmt_id],
    }
}

fn stmt_has_ctl_ops(ast: &RuntimeAst, stmt_id: RuntimeNodeId, info: &CpsInfo) -> bool {
    match ast.get_stmt(stmt_id) {
        Some(RuntimeStmt::Block(stmts)) => {
            let stmts = stmts.clone();
            stmts.iter().any(|&s| stmt_has_ctl_ops(ast, s, info))
        }
        Some(RuntimeStmt::ExprStmt(expr)) => expr_has_ctl_ops(ast, *expr, info),
        Some(RuntimeStmt::VarDecl { expr, .. }) => expr_has_ctl_ops(ast, *expr, info),
        Some(RuntimeStmt::Assign { expr, .. }) => expr_has_ctl_ops(ast, *expr, info),
        Some(RuntimeStmt::WhileLoop { cond, body }) => {
            expr_has_ctl_ops(ast, *cond, info) || stmt_has_ctl_ops(ast, *body, info)
        }
        Some(RuntimeStmt::If { cond, body, else_branch }) => {
            expr_has_ctl_ops(ast, *cond, info)
                || stmt_has_ctl_ops(ast, *body, info)
                || else_branch.map_or(false, |e| stmt_has_ctl_ops(ast, e, info))
        }
        _ => false,
    }
}

fn expr_has_ctl_ops(ast: &RuntimeAst, expr_id: RuntimeNodeId, info: &CpsInfo) -> bool {
    match ast.get_expr(expr_id) {
        Some(RuntimeExpr::Call { callee, args }) => {
            let is_ctl = info.ctl_ops.contains(callee.as_str());
            let args = args.clone();
            is_ctl || args.iter().any(|&a| expr_has_ctl_ops(ast, a, info))
        }
        Some(RuntimeExpr::Lambda { body, .. }) => stmt_has_ctl_ops(ast, *body, info),
        _ => false,
    }
}

fn collect_stmt_refs(
    ast: &RuntimeAst,
    stmt_id: RuntimeNodeId,
    bound: &BTreeSet<String>,
    refs: &mut BTreeSet<String>,
) {
    match ast.get_stmt(stmt_id) {
        Some(RuntimeStmt::Block(stmts)) => {
            let stmts = stmts.clone();
            for s in stmts { collect_stmt_refs(ast, s, bound, refs); }
        }
        Some(RuntimeStmt::ExprStmt(expr)) => collect_expr_refs(ast, *expr, bound, refs),
        Some(RuntimeStmt::VarDecl { expr, .. }) => collect_expr_refs(ast, *expr, bound, refs),
        Some(RuntimeStmt::Assign { name, expr }) => {
            if !bound.contains(name) { refs.insert(name.clone()); }
            collect_expr_refs(ast, *expr, bound, refs);
        }
        Some(RuntimeStmt::WhileLoop { cond, body }) => {
            collect_expr_refs(ast, *cond, bound, refs);
            collect_stmt_refs(ast, *body, bound, refs);
        }
        Some(RuntimeStmt::If { cond, body, else_branch }) => {
            collect_expr_refs(ast, *cond, bound, refs);
            collect_stmt_refs(ast, *body, bound, refs);
            if let Some(e) = else_branch { collect_stmt_refs(ast, *e, bound, refs); }
        }
        Some(RuntimeStmt::ForEach { var, iterable, body }) => {
            collect_expr_refs(ast, *iterable, bound, refs);
            let mut inner_bound = bound.clone();
            inner_bound.insert(var.clone());
            collect_stmt_refs(ast, *body, &inner_bound, refs);
        }
        Some(RuntimeStmt::Match { scrutinee, arms }) => {
            collect_expr_refs(ast, *scrutinee, bound, refs);
            let arms = arms.clone();
            for arm in &arms {
                let mut arm_bound = bound.clone();
                match &arm.pattern {
                    crate::frontend::meta_ast::Pattern::Enum { bindings, .. } => {
                        match bindings {
                            crate::frontend::meta_ast::VariantBindings::Tuple(names)
                            | crate::frontend::meta_ast::VariantBindings::Struct(names) => {
                                arm_bound.extend(names.iter().cloned());
                            }
                            crate::frontend::meta_ast::VariantBindings::Unit => {}
                        }
                    }
                    crate::frontend::meta_ast::Pattern::Wildcard => {}
                }
                collect_stmt_refs(ast, arm.body, &arm_bound, refs);
            }
        }
        Some(RuntimeStmt::Resume(Some(expr))) => {
            collect_expr_refs(ast, *expr, bound, refs);
        }
        Some(RuntimeStmt::Print(expr)) => {
            collect_expr_refs(ast, *expr, bound, refs);
        }
        _ => {}
    }
}

fn collect_expr_refs(
    ast: &RuntimeAst,
    expr_id: RuntimeNodeId,
    bound: &BTreeSet<String>,
    refs: &mut BTreeSet<String>,
) {
    match ast.get_expr(expr_id) {
        Some(RuntimeExpr::Variable(name)) => {
            if !bound.contains(name) { refs.insert(name.clone()); }
        }
        Some(RuntimeExpr::Call { callee: _, args }) => {
            let args = args.clone();
            for a in args { collect_expr_refs(ast, a, bound, refs); }
        }
        Some(RuntimeExpr::Add(a, b) | RuntimeExpr::Sub(a, b)
            | RuntimeExpr::Mult(a, b) | RuntimeExpr::Div(a, b)
            | RuntimeExpr::Lt(a, b) | RuntimeExpr::Gt(a, b)
            | RuntimeExpr::Lte(a, b) | RuntimeExpr::Gte(a, b)
            | RuntimeExpr::Equals(a, b) | RuntimeExpr::NotEquals(a, b)
            | RuntimeExpr::And(a, b) | RuntimeExpr::Or(a, b)) => {
            let (a, b) = (*a, *b);
            collect_expr_refs(ast, a, bound, refs);
            collect_expr_refs(ast, b, bound, refs);
        }
        Some(RuntimeExpr::Not(e)) => collect_expr_refs(ast, *e, bound, refs),
        Some(RuntimeExpr::ResumeExpr(Some(e))) => collect_expr_refs(ast, *e, bound, refs),
        _ => {}
    }
}
