use std::collections::BTreeSet;

use crate::semantics::cps::effect_marker::CpsInfo;
use crate::semantics::meta::runtime_ast::{RuntimeAst, RuntimeExpr, RuntimeStmt};
use crate::util::id_provider::IdProvider;

// ── Public entry point ────────────────────────────────────────────────────────

/// Apply the full CPS transform to `ast` in-place, including converting while loops
/// that contain ctl ops into tail-recursive helper functions.
///
/// Use this for the **codegen** (LLVM) path.
///
/// For every function in `info.cps_fns`:
///   - Adds a `__k` continuation parameter.
///   - Wraps each sequential ctl op / cps-fn call with a lambda continuation.
///   - Converts while loops with ctl ops to tail-recursive helper functions.
///   - Replaces `return x` with `__k(x)`.
///   - Appends `__k(unit)` if the body falls off the end.
///
/// Also transforms the top-level statement sequence so that calls to CPS functions
/// at the root level are wrapped with a lambda capturing the remaining statements.
pub fn transform(ast: &mut RuntimeAst, info: &CpsInfo) {
    transform_internal(ast, info, true);
}

/// Apply the CPS transform to `ast` in-place **without** converting while loops to
/// tail-recursive helpers.
///
/// Use this for the **interpreter** path. The interpreter's replay-stack mechanism
/// already handles ctl ops inside while loops without needing loop-to-recursion
/// conversion. Converting loops to recursion causes deep Rust call-stack nesting
/// that can overflow for even a modest number of iterations in debug builds.
pub fn transform_interpreter(ast: &mut RuntimeAst, info: &CpsInfo) {
    transform_internal(ast, info, false);
}

fn transform_internal(ast: &mut RuntimeAst, info: &CpsInfo, convert_while_loops: bool) {
    // Run whenever there are ctl ops (even if no function is CPS-marked),
    // so that top-level ctl calls get wrapped with continuation lambdas.
    if info.cps_fns.is_empty() && info.ctl_ops.is_empty() {
        return;
    }

    let max_id = ast.stmts.keys().chain(ast.exprs.keys()).copied().max().unwrap_or(0);
    let mut t = CpsTransform {
        info,
        ids: IdProvider::starting_from(max_id + 1),
        new_fndecls: Vec::new(),
        convert_while_loops,
        current_k_name: "__k".to_string(), // overwritten per-function in transform_fn_decl
    };

    // Transform all CPS FnDecl bodies.
    let fn_stmt_ids: Vec<usize> = ast.stmts.keys().copied().collect();
    for stmt_id in fn_stmt_ids {
        if let Some(RuntimeStmt::FnDecl { name, .. }) = ast.get_stmt(stmt_id) {
            if info.cps_fns.contains(name.as_str()) {
                t.transform_fn_decl(ast, stmt_id);
            }
        }
    }

    // Transform the top-level sequence for any CPS calls there.
    let root = std::mem::take(&mut ast.sem_root_stmts);
    ast.sem_root_stmts = t.transform_stmts(ast, root, false);

    // Append any helper FnDecls generated by loop-to-recursion transforms.
    // Done after the top-level transform so they are never swept into continuation lambdas.
    ast.sem_root_stmts.extend(t.new_fndecls.iter().copied());
}

// ── Internal state ────────────────────────────────────────────────────────────

struct CpsTransform<'a> {
    info: &'a CpsInfo,
    ids: IdProvider,
    /// New FnDecl stmt ids created by loop-to-recursion transforms.
    /// Appended to `ast.sem_root_stmts` after all transforms complete,
    /// so they never appear as "suffix" inside continuation lambdas.
    new_fndecls: Vec<usize>,
    /// When true, while loops containing ctl ops are converted to tail-recursive
    /// helper functions. Set to false for the interpreter path, which handles
    /// ctl-in-loops via its existing replay-stack mechanism.
    convert_while_loops: bool,
    /// The continuation parameter name for the CPS function currently being
    /// transformed.  Set by `transform_fn_decl` to `"__k_<stmt_id>"` so that
    /// every CPS function gets a *unique* k-name.  This prevents the closure
    /// lambda `fn(r){ return __k_73(Maybe::Just(r)); }` from shadowing itself
    /// when it is passed as the `__k_<other_id>` parameter of a callee CPS
    /// function — which would cause infinite recursion at runtime because the
    /// interpreter resolves free variables through the dynamic scope chain.
    current_k_name: String,
}

struct CpsCall {
    callee: String,
    args: Vec<usize>,
    /// The name to bind the resumed value to; `None` for bare expression statements.
    binding: Option<String>,
}

impl<'a> CpsTransform<'a> {
    // ── FnDecl ────────────────────────────────────────────────────────────────

    fn transform_fn_decl(&mut self, ast: &mut RuntimeAst, stmt_id: usize) {
        let (name, mut params, type_params, body_id) =
            match ast.get_stmt(stmt_id).unwrap().clone() {
                RuntimeStmt::FnDecl { name, params, type_params, body } => {
                    (name, params, type_params, body)
                }
                _ => return,
            };

        // Use a unique k-name per function to prevent closures from shadowing
        // each other when passed as __k arguments to other CPS functions.
        let k_name = format!("__k_{}", stmt_id);
        self.current_k_name = k_name.clone();
        params.push(k_name);

        let stmts = match ast.get_stmt(body_id).unwrap().clone() {
            RuntimeStmt::Block(s) => s,
            _ => vec![body_id],
        };

        let transformed = self.transform_stmts(ast, stmts, true);
        let new_body = self.fresh_stmt(ast, RuntimeStmt::Block(transformed));

        ast.insert_stmt(
            stmt_id,
            RuntimeStmt::FnDecl { name, params, type_params, body: new_body },
        );
    }

    // ── Statement sequence ────────────────────────────────────────────────────

    /// Transform a flat statement list.
    ///
    /// `is_cps_body`: true when we are inside a CPS function — `return` gets
    /// rewritten to `__k(x)` and a trailing `__k(unit)` is appended if needed.
    fn transform_stmts(
        &mut self,
        ast: &mut RuntimeAst,
        stmts: Vec<usize>,
        is_cps_body: bool,
    ) -> Vec<usize> {
        // Flatten top-level Block wrappers so that WhileLoops and ctl calls
        // inside nested blocks are visible to the CPS transform.
        let stmts = flatten_stmt_list(ast, stmts);

        let mut result: Vec<usize> = Vec::new();

        let mut i = 0;
        while i < stmts.len() {
            let stmt_id = stmts[i];

            // Return inside a CPS body → __k(value); terminate sequence.
            if is_cps_body {
                if let Some(k_call) = self.try_transform_return(ast, stmt_id) {
                    result.push(k_call);
                    return result;
                }
            }

            // WhileLoop containing ctl ops → convert to tail-recursive helper fn.
            // Only when convert_while_loops is enabled (codegen path).
            // The interpreter handles ctl ops in loops via its replay-stack mechanism.
            if self.convert_while_loops
                && matches!(ast.get_stmt(stmt_id), Some(RuntimeStmt::WhileLoop { .. }))
                && stmt_has_ctl_ops(ast, stmt_id, self.info)
            {
                let suffix = stmts[i + 1..].to_vec();
                let replacement = self.transform_while_loop(ast, stmt_id, &suffix, is_cps_body);
                result.extend(replacement);
                // suffix is consumed inside transform_while_loop
                return result;
            }

            // If statement whose condition IS a ctl op call → hoist condition into CPS.
            // E.g. `if (flip()) { A } else { B }` becomes `flip(λ(__result) { if(__result) { A } else { B } })`.
            if let Some(RuntimeStmt::If { cond, body, else_branch }) = ast.get_stmt(stmt_id) {
                let (cond_id, body_id, else_id) = (*cond, *body, *else_branch);
                if let Some(RuntimeExpr::Call { callee, args }) = ast.get_expr(cond_id) {
                    if self.is_cps_callee(callee) {
                        let callee = callee.clone();
                        let ctl_args = args.clone();
                        let suffix = stmts[i + 1..].to_vec();
                        let replacement = self.transform_if_ctl_cond(
                            ast, callee, ctl_args, body_id, else_id, suffix, is_cps_body,
                        );
                        result.extend(replacement);
                        return result;
                    }
                }
            }

            // Sequential CPS call → wrap rest as continuation lambda.
            //
            // Two cases:
            //   1. Inside a CPS body (is_cps_body = true): always wrap; emit as `return`.
            //   2. At root level (is_cps_body = false): wrap only for non-handle-block
            //      functions.  `__handle_N` wrappers generated for handle blocks need
            //      identity injection (so the result is assigned to `var x = __handle_N()`
            //      and the multi-shot flatmap can use resume's return value).  Direct
            //      ctl-calling functions from old-style `with ctl` code (e.g. `find_matching`)
            //      need wrapping so the suffix (like `print(result)`) becomes the terminal
            //      continuation, triggering side-effects as the ctl ops resume.
            let is_handle_callee = match ast.get_stmt(stmt_id) {
                Some(RuntimeStmt::VarDecl { expr, .. }) | Some(RuntimeStmt::ExprStmt(expr)) => {
                    matches!(ast.get_expr(*expr),
                        Some(RuntimeExpr::Call { callee, .. }) if callee.starts_with("__handle_"))
                }
                _ => false,
            };
            let should_extract = is_cps_body || !is_handle_callee;

            if should_extract {
                if let Some(call) = self.extract_cps_call(ast, stmt_id) {
                    let suffix = stmts[i + 1..].to_vec();
                    let suffix_transformed = self.transform_stmts(ast, suffix, is_cps_body);

                    let body_stmts = if is_cps_body && suffix_transformed.is_empty() {
                        // End of CPS function with no remaining statements: call __k(unit).
                        vec![self.make_k_unit_call(ast)]
                    } else {
                        suffix_transformed
                    };

                    let cont_param = call.binding.unwrap_or_else(|| "__".to_string());
                    let lambda_body = self.fresh_stmt(ast, RuntimeStmt::Block(body_stmts));
                    let lambda = self.fresh_expr(
                        ast,
                        RuntimeExpr::Lambda { params: vec![cont_param], body: lambda_body },
                    );

                    let mut new_args = call.args;
                    new_args.push(lambda);
                    let call_expr =
                        self.fresh_expr(ast, RuntimeExpr::Call { callee: call.callee, args: new_args });
                    // Inside CPS bodies, emit `return cps_call(...)` so the value propagates back
                    // through `call_value` to any `resume(x)` expression in a handler.
                    // At root level, emit as a plain ExprStmt — the continuation's side-effects
                    // are what matter; the return value isn't assigned.
                    let call_stmt = if is_cps_body {
                        self.fresh_stmt(ast, RuntimeStmt::Return(Some(call_expr)))
                    } else {
                        self.fresh_stmt(ast, RuntimeStmt::ExprStmt(call_expr))
                    };

                    result.push(call_stmt);
                    return result; // Everything after is inside the lambda.
                }
            }

            result.push(stmt_id);
            i += 1;
        }

        // End of a CPS function body with no explicit return or ctl call — append __k(unit).
        if is_cps_body {
            result.push(self.make_k_unit_call(ast));
        }

        result
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /// If `stmt_id` is a `Return`, rewrite it to `return __k_N(value)` and return the new stmt ID.
    /// Using `Return` (not `ExprStmt`) so the value propagates back through `call_value`.
    fn try_transform_return(&mut self, ast: &mut RuntimeAst, stmt_id: usize) -> Option<usize> {
        match ast.get_stmt(stmt_id)?.clone() {
            RuntimeStmt::Return(opt_expr) => {
                let val = opt_expr.unwrap_or_else(|| self.fresh_expr(ast, RuntimeExpr::Unit));
                let k = self.current_k_name.clone();
                let call = self.fresh_expr(
                    ast,
                    RuntimeExpr::Call { callee: k, args: vec![val] },
                );
                Some(self.fresh_stmt(ast, RuntimeStmt::Return(Some(call))))
            }
            _ => None,
        }
    }

    /// Emit `return __k_N(unit)`.
    fn make_k_unit_call(&mut self, ast: &mut RuntimeAst) -> usize {
        let unit = self.fresh_expr(ast, RuntimeExpr::Unit);
        let k = self.current_k_name.clone();
        let call = self.fresh_expr(ast, RuntimeExpr::Call { callee: k, args: vec![unit] });
        self.fresh_stmt(ast, RuntimeStmt::Return(Some(call)))
    }

    /// If `stmt_id` is a VarDecl or ExprStmt whose expression is a call to a ctl op
    /// or CPS function, return the call info. Otherwise `None`.
    fn extract_cps_call(&self, ast: &RuntimeAst, stmt_id: usize) -> Option<CpsCall> {
        match ast.get_stmt(stmt_id)? {
            RuntimeStmt::VarDecl { name, expr } => {
                if let Some(RuntimeExpr::Call { callee, args }) = ast.get_expr(*expr) {
                    if self.is_cps_callee(callee) {
                        return Some(CpsCall {
                            callee: callee.clone(),
                            args: args.clone(),
                            binding: Some(name.clone()),
                        });
                    }
                }
                None
            }
            RuntimeStmt::ExprStmt(expr) => {
                if let Some(RuntimeExpr::Call { callee, args }) = ast.get_expr(*expr) {
                    if self.is_cps_callee(callee) {
                        return Some(CpsCall {
                            callee: callee.clone(),
                            args: args.clone(),
                            binding: None,
                        });
                    }
                }
                None
            }
            _ => None,
        }
    }

    fn is_cps_callee(&self, callee: &str) -> bool {
        self.info.ctl_ops.contains(callee) || self.info.cps_fns.contains(callee)
    }

    // ── WhileLoop → tail-recursive helper function ───────────────────────────

    /// Convert a `while` loop containing ctl ops into a call to a new recursive
    /// helper function in CPS style.
    ///
    /// Given:
    ///   ```text
    ///   while (cond) { [body containing yield(...)] [assigns: v = update(v)] }
    ///   ```
    /// Produces:
    ///   ```text
    ///   fn __loop_N(mutable_vars..., captured_vars..., __k) {
    ///       if (cond) {
    ///           [CPS-transformed body where continuation is __loop_N(updated_v, ...)]
    ///       } else {
    ///           __k(unit)
    ///       }
    ///   }
    ///   // In the caller's body:
    ///   __loop_N(current_mutable_vars..., captured_vars..., loop_k)
    ///   ```
    fn transform_while_loop(
        &mut self,
        ast: &mut RuntimeAst,
        while_stmt_id: usize,
        suffix: &[usize],
        is_cps_body: bool,
    ) -> Vec<usize> {
        let (cond_id, body_id) = match ast.get_stmt(while_stmt_id) {
            Some(RuntimeStmt::WhileLoop { cond, body }) => (*cond, *body),
            _ => return vec![while_stmt_id],
        };

        // Flatten loop body into a linear list of statements.
        let flat_body = flatten_stmt_list(ast, vec![body_id]);

        // Separate top-level Assign statements (loop updates) from everything else.
        let mut assigns: Vec<(String, usize)> = Vec::new(); // (var_name, new_val_expr)
        let mut non_assigns: Vec<usize> = Vec::new();
        for &sid in &flat_body {
            match ast.get_stmt(sid) {
                Some(RuntimeStmt::Assign { name, expr }) => {
                    assigns.push((name.clone(), *expr));
                }
                _ => non_assigns.push(sid),
            }
        }

        // Collect free variables referenced in condition + body, excluding
        // the mutable (assigned) variables (which become explicit params).
        let assigned_names: BTreeSet<String> =
            assigns.iter().map(|(n, _)| n.clone()).collect();
        // VarDecls inside the loop body are local — exclude them from captured_vars.
        let locally_declared: BTreeSet<String> = flat_body.iter()
            .filter_map(|&sid| {
                if let Some(RuntimeStmt::VarDecl { name, .. }) = ast.get_stmt(sid) {
                    Some(name.clone())
                } else {
                    None
                }
            })
            .collect();
        let mut refs: BTreeSet<String> = BTreeSet::new();
        collect_stmt_refs(ast, body_id, &assigned_names, &mut refs);
        collect_expr_refs(ast, cond_id, &assigned_names, &mut refs);
        // Remove ctl ops (global functions), the outer k-name, and loop-body-local VarDecls.
        let outer_k = self.current_k_name.clone();
        let captured_vars: Vec<String> = refs
            .into_iter()
            .filter(|r| {
                !self.info.ctl_ops.contains(r.as_str())
                    && r.as_str() != outer_k.as_str()
                    && !locally_declared.contains(r.as_str())
            })
            .collect();

        // Helper function name is deterministic on the while stmt id.
        let helper_name = format!("__loop_{}", while_stmt_id);

        // Helper params: mutable_vars... + captured_vars... + __k
        let mut helper_params: Vec<String> =
            assigns.iter().map(|(n, _)| n.clone()).collect();
        helper_params.extend(captured_vars.iter().cloned());
        helper_params.push("__k".to_string());

        // Build the args for the recursive call inside the continuation lambda.
        // Arg order matches helper_params (minus __k which is re-used unchanged).
        let mut recursive_args: Vec<usize> = Vec::new();
        for (_, update_expr) in &assigns {
            recursive_args.push(*update_expr); // reuse the existing update expr node
        }
        for cap in &captured_vars {
            recursive_args.push(self.fresh_expr(ast, RuntimeExpr::Variable(cap.clone())));
        }
        recursive_args.push(self.fresh_expr(ast, RuntimeExpr::Variable("__k".to_string())));
        let recursive_call_expr = self.fresh_expr(ast, RuntimeExpr::Call {
            callee: helper_name.clone(),
            args: recursive_args,
        });
        let recursive_call_stmt = self.fresh_stmt(ast, RuntimeStmt::ExprStmt(recursive_call_expr));

        // CPS-transform the non-assign body with the recursive call as the suffix.
        // is_cps_body=false — the recursive call is the explicit continuation.
        let mut body_for_cps = non_assigns;
        body_for_cps.push(recursive_call_stmt);
        let cps_body = self.transform_stmts(ast, body_for_cps, false);

        // True branch: the CPS-transformed loop body.
        let true_block = self.fresh_stmt(ast, RuntimeStmt::Block(cps_body));

        // False branch: call the continuation with unit (loop done).
        let unit_e = self.fresh_expr(ast, RuntimeExpr::Unit);
        let k_done = self.fresh_expr(ast, RuntimeExpr::Call {
            callee: "__k".to_string(),
            args: vec![unit_e],
        });
        let k_done_stmt = self.fresh_stmt(ast, RuntimeStmt::ExprStmt(k_done));
        let false_block = self.fresh_stmt(ast, RuntimeStmt::Block(vec![k_done_stmt]));

        // If statement: if (cond) { true_block } else { false_block }
        let if_stmt = self.fresh_stmt(ast, RuntimeStmt::If {
            cond: cond_id,
            body: true_block,
            else_branch: Some(false_block),
        });

        // Helper function body and declaration.
        let helper_body = self.fresh_stmt(ast, RuntimeStmt::Block(vec![if_stmt]));
        let helper_decl = self.fresh_stmt(ast, RuntimeStmt::FnDecl {
            name: helper_name.clone(),
            params: helper_params.clone(),
            type_params: vec![],
            body: helper_body,
        });
        // Defer registration — appended to sem_root_stmts after the top-level
        // transform completes, so it never appears as suffix inside a lambda.
        self.new_fndecls.push(helper_decl);

        // Determine the loop's continuation (__k for the helper):
        //   - Empty suffix + CPS body: pass outer k-param directly (most common case).
        //   - Otherwise: wrap suffix in a lambda that becomes the loop's __k.
        let loop_k = if suffix.is_empty() && is_cps_body {
            self.fresh_expr(ast, RuntimeExpr::Variable(outer_k))
        } else {
            let suffix_transformed = self.transform_stmts(ast, suffix.to_vec(), is_cps_body);
            let suffix_body = self.fresh_stmt(ast, RuntimeStmt::Block(suffix_transformed));
            self.fresh_expr(ast, RuntimeExpr::Lambda {
                params: vec!["__".to_string()],
                body: suffix_body,
            })
        };

        // Build the initial call that replaces the while loop in the caller.
        // Pass current values of mutable vars, then captured vars, then loop_k.
        let mut init_args: Vec<usize> = Vec::new();
        for (var_name, _) in &assigns {
            init_args.push(self.fresh_expr(ast, RuntimeExpr::Variable(var_name.clone())));
        }
        for cap in &captured_vars {
            init_args.push(self.fresh_expr(ast, RuntimeExpr::Variable(cap.clone())));
        }
        init_args.push(loop_k);
        let init_call = self.fresh_expr(ast, RuntimeExpr::Call {
            callee: helper_name,
            args: init_args,
        });
        let init_stmt = self.fresh_stmt(ast, RuntimeStmt::ExprStmt(init_call));

        vec![init_stmt]
    }

    // ── If with ctl condition ─────────────────────────────────────────────────

    /// Transform `if (ctl_op(args...)) { body } else { else_branch }` into
    /// `ctl_op(args..., λ(__result) { if (__result) { body } else { else_branch } suffix... })`.
    fn transform_if_ctl_cond(
        &mut self,
        ast: &mut RuntimeAst,
        callee: String,
        ctl_args: Vec<usize>,
        body: usize,
        else_branch: Option<usize>,
        suffix: Vec<usize>,
        is_cps_body: bool,
    ) -> Vec<usize> {
        // Variable that receives the ctl op's return value.
        let result_var = "__result".to_string();
        let result_var_expr = self.fresh_expr(ast, RuntimeExpr::Variable(result_var.clone()));

        // Rewrite the If to use the fresh variable as its condition.
        let new_if = self.fresh_stmt(ast, RuntimeStmt::If {
            cond: result_var_expr,
            body,
            else_branch,
        });

        // Continuation body: [new_if, ...suffix].
        let mut cont_body = vec![new_if];
        cont_body.extend(suffix);
        let cont_transformed = self.transform_stmts(ast, cont_body, is_cps_body);

        // Wrap in lambda.
        let lambda_body = self.fresh_stmt(ast, RuntimeStmt::Block(cont_transformed));
        let lambda = self.fresh_expr(ast, RuntimeExpr::Lambda {
            params: vec![result_var],
            body: lambda_body,
        });

        // Build the ctl op call with the continuation appended.
        let mut new_args = ctl_args;
        new_args.push(lambda);
        let call_expr = self.fresh_expr(ast, RuntimeExpr::Call { callee, args: new_args });
        let call_stmt = self.fresh_stmt(ast, RuntimeStmt::ExprStmt(call_expr));

        vec![call_stmt]
    }

    fn fresh_expr(&mut self, ast: &mut RuntimeAst, expr: RuntimeExpr) -> usize {
        let id = self.ids.next();
        ast.insert_expr(id, expr);
        id
    }

    fn fresh_stmt(&mut self, ast: &mut RuntimeAst, stmt: RuntimeStmt) -> usize {
        let id = self.ids.next();
        ast.insert_stmt(id, stmt);
        id
    }
}

// ── Free-standing helpers ─────────────────────────────────────────────────────

/// Recursively flatten Block wrappers into a flat statement list.
fn flatten_stmt_list(ast: &RuntimeAst, stmts: Vec<usize>) -> Vec<usize> {
    stmts.into_iter()
        .flat_map(|id| flatten_one(ast, id))
        .collect()
}

fn flatten_one(ast: &RuntimeAst, stmt_id: usize) -> Vec<usize> {
    match ast.get_stmt(stmt_id) {
        Some(RuntimeStmt::Block(inner)) => {
            let inner = inner.clone();
            inner.into_iter().flat_map(|id| flatten_one(ast, id)).collect()
        }
        _ => vec![stmt_id],
    }
}

/// Returns true if any statement in the subtree rooted at `stmt_id` calls a ctl op.
fn stmt_has_ctl_ops(ast: &RuntimeAst, stmt_id: usize, info: &CpsInfo) -> bool {
    match ast.get_stmt(stmt_id) {
        Some(RuntimeStmt::Block(stmts)) => {
            let stmts = stmts.clone();
            stmts.iter().any(|&s| stmt_has_ctl_ops(ast, s, info))
        }
        Some(RuntimeStmt::ExprStmt(expr)) => expr_has_ctl_ops(ast, *expr, info),
        Some(RuntimeStmt::VarDecl { expr, .. }) => expr_has_ctl_ops(ast, *expr, info),
        Some(RuntimeStmt::Assign { expr, .. }) => expr_has_ctl_ops(ast, *expr, info),
        Some(RuntimeStmt::WhileLoop { cond, body }) => {
            expr_has_ctl_ops(ast, *cond, info) || stmt_has_ctl_ops(ast, *body, info)
        }
        Some(RuntimeStmt::If { cond, body, else_branch }) => {
            expr_has_ctl_ops(ast, *cond, info)
                || stmt_has_ctl_ops(ast, *body, info)
                || else_branch.map_or(false, |e| stmt_has_ctl_ops(ast, e, info))
        }
        _ => false,
    }
}

fn expr_has_ctl_ops(ast: &RuntimeAst, expr_id: usize, info: &CpsInfo) -> bool {
    match ast.get_expr(expr_id) {
        Some(RuntimeExpr::Call { callee, args }) => {
            let is_ctl = info.ctl_ops.contains(callee.as_str());
            let args = args.clone();
            is_ctl || args.iter().any(|&a| expr_has_ctl_ops(ast, a, info))
        }
        Some(RuntimeExpr::Lambda { body, .. }) => stmt_has_ctl_ops(ast, *body, info),
        _ => false,
    }
}

/// Collect all Variable names referenced in a statement subtree,
/// excluding those in `bound`.
fn collect_stmt_refs(
    ast: &RuntimeAst,
    stmt_id: usize,
    bound: &BTreeSet<String>,
    refs: &mut BTreeSet<String>,
) {
    match ast.get_stmt(stmt_id) {
        Some(RuntimeStmt::Block(stmts)) => {
            let stmts = stmts.clone();
            for s in stmts { collect_stmt_refs(ast, s, bound, refs); }
        }
        Some(RuntimeStmt::ExprStmt(expr)) => collect_expr_refs(ast, *expr, bound, refs),
        Some(RuntimeStmt::VarDecl { expr, .. }) => collect_expr_refs(ast, *expr, bound, refs),
        Some(RuntimeStmt::Assign { name, expr }) => {
            if !bound.contains(name) { refs.insert(name.clone()); }
            collect_expr_refs(ast, *expr, bound, refs);
        }
        Some(RuntimeStmt::WhileLoop { cond, body }) => {
            collect_expr_refs(ast, *cond, bound, refs);
            collect_stmt_refs(ast, *body, bound, refs);
        }
        Some(RuntimeStmt::If { cond, body, else_branch }) => {
            collect_expr_refs(ast, *cond, bound, refs);
            collect_stmt_refs(ast, *body, bound, refs);
            if let Some(e) = else_branch { collect_stmt_refs(ast, *e, bound, refs); }
        }
        Some(RuntimeStmt::ForEach { var, iterable, body }) => {
            collect_expr_refs(ast, *iterable, bound, refs);
            let mut inner_bound = bound.clone();
            inner_bound.insert(var.clone());
            collect_stmt_refs(ast, *body, &inner_bound, refs);
        }
        Some(RuntimeStmt::Match { scrutinee, arms }) => {
            collect_expr_refs(ast, *scrutinee, bound, refs);
            let arms = arms.clone();
            for arm in &arms {
                let mut arm_bound = bound.clone();
                match &arm.pattern {
                    crate::frontend::meta_ast::Pattern::Enum { bindings, .. } => {
                        match bindings {
                            crate::frontend::meta_ast::VariantBindings::Tuple(names)
                            | crate::frontend::meta_ast::VariantBindings::Struct(names) => {
                                arm_bound.extend(names.iter().cloned());
                            }
                            crate::frontend::meta_ast::VariantBindings::Unit => {}
                        }
                    }
                    crate::frontend::meta_ast::Pattern::Wildcard => {}
                }
                collect_stmt_refs(ast, arm.body, &arm_bound, refs);
            }
        }
        Some(RuntimeStmt::Resume(Some(expr))) => {
            collect_expr_refs(ast, *expr, bound, refs);
        }
        Some(RuntimeStmt::Print(expr)) => {
            collect_expr_refs(ast, *expr, bound, refs);
        }
        _ => {}
    }
}

fn collect_expr_refs(
    ast: &RuntimeAst,
    expr_id: usize,
    bound: &BTreeSet<String>,
    refs: &mut BTreeSet<String>,
) {
    match ast.get_expr(expr_id) {
        Some(RuntimeExpr::Variable(name)) => {
            if !bound.contains(name) { refs.insert(name.clone()); }
        }
        Some(RuntimeExpr::Call { callee: _, args }) => {
            // Don't include the callee — it's a function name, not a local variable.
            let args = args.clone();
            for a in args { collect_expr_refs(ast, a, bound, refs); }
        }
        Some(RuntimeExpr::Add(a, b) | RuntimeExpr::Sub(a, b)
            | RuntimeExpr::Mult(a, b) | RuntimeExpr::Div(a, b)
            | RuntimeExpr::Lt(a, b) | RuntimeExpr::Gt(a, b)
            | RuntimeExpr::Lte(a, b) | RuntimeExpr::Gte(a, b)
            | RuntimeExpr::Equals(a, b) | RuntimeExpr::NotEquals(a, b)
            | RuntimeExpr::And(a, b) | RuntimeExpr::Or(a, b)) => {
            let (a, b) = (*a, *b);
            collect_expr_refs(ast, a, bound, refs);
            collect_expr_refs(ast, b, bound, refs);
        }
        Some(RuntimeExpr::Not(e)) => collect_expr_refs(ast, *e, bound, refs),
        Some(RuntimeExpr::ResumeExpr(Some(e))) => collect_expr_refs(ast, *e, bound, refs),
        _ => {}
    }
}
